### ISSUE TITLE
[bug] new cheshire_cat_ai sdk version not working anymore

### ISSUE THREAD

**Issue by AlessandroSpallina** [Pingdred/Meowgram#3]
After the update of https://github.com/cheshire-cat-ai/api-client-py/releases to v1.4 the telegram bot is not starting anymore. Enforcing the v1.3.0 in requirements.txt will return the bot to the proper behaviour.

**Comment by nicola-corbellini** [comment]
Do you have the log of the error please?

**Comment by Pingdred** [comment]
My bad, I updated the bot but I haven't pushed the changes yet, maximum an hour and I'll solve everything

**Comment by Pingdred** [comment]
@AlessandroSpallina I just pushed, check if everything works

**Comment by AlessandroSpallina** [comment]
Yup, everything is working smoothly now
